/**
 * Result → human artifacts (TRD §11, §20). Builds the PR title, PR body, and
 * the summary markdown. Used by the git finalize step and the `summarize` CLI.
 */
import type { Task, Result, CommandExecution } from "./contracts.ts";

function shortTitle(summary: string): string {
  const firstLine = (summary.split("\n")[0] ?? "").trim();
  return firstLine.length > 72 ? firstLine.slice(0, 69) + "…" : firstLine || "automated change";
}

export function buildPrTitle(task: Task, result: Result): string {
  return `[agentic] issue-${task.issue_id}: ${shortTitle(result.summary)}`;
}

function execRow(e: CommandExecution): string {
  const status = e.exit_code === 0 ? "✅ pass" : "❌ fail";
  return `| ${e.name} | \`${e.command}\` | ${status} | ${e.duration_ms} ms |`;
}

function execTable(result: Result): string {
  const rows: CommandExecution[] = [...result.tests_executed];
  if (result.lint_executed) rows.push(result.lint_executed);
  if (result.typecheck_executed) rows.push(result.typecheck_executed);
  if (rows.length === 0) return "_No test/lint/typecheck commands were run._";
  return ["| Check | Command | Result | Duration |", "|---|---|---|---|", ...rows.map(execRow)].join("\n");
}

function bulletList(items: string[], emptyText: string): string {
  return items.length === 0 ? emptyText : items.map((i) => `- ${i}`).join("\n");
}

export function buildSummaryMarkdown(result: Result): string {
  return `# pi-coder run — task ${result.task_id}

**Status:** ${result.status}

## Summary
${result.summary}

## Changed files (${result.diff_stats.files}, +${result.diff_stats.additions}/-${result.diff_stats.deletions})
${bulletList(result.changed_files, "_none_")}

## Checks
${execTable(result)}

## Code review
${result.review.passed ? "✅ Passed" : "⚠️ Not passed"} after ${result.review.iterations} iteration(s).
${bulletList(result.review.findings, "_no findings_")}

## Risks
${bulletList(result.risks, "_none noted_")}

## Next steps
${bulletList(result.next_steps, "_none_")}
`;
}

export function buildPrBody(task: Task, result: Result): string {
  const repro =
    result.tests_executed[0]?.command ??
    "See the project's standard test command.";
  return `## Summary
${result.summary}

## Task
- Issue: \`${task.issue_id}\`
- Instructions: ${task.instructions}
- Acceptance criteria: ${task.acceptance_criteria ?? "_n/a_"}

## Checks
${execTable(result)}

## Code review
${result.review.passed ? "✅ Passed" : "⚠️ Not passed"} after ${result.review.iterations} iteration(s).
${bulletList(result.review.findings, "_no findings_")}

## Risks & follow-ups
${bulletList([...result.risks, ...result.next_steps], "_none noted_")}

## Reproduction
\`\`\`
${repro}
\`\`\`

---
🤖 Generated by pi-coder. Status: **${result.status}**. Diff: +${result.diff_stats.additions}/-${result.diff_stats.deletions} across ${result.diff_stats.files} file(s).
${result.blocked_by.length > 0 ? `\n⚠️ Blocked by: ${result.blocked_by.join(", ")}` : ""}`;
}
